# Modify the version if you don't use MRI 2.1.
inherit_from: 
  - .rubocop.ruby.yml
  - .rubocop.rspec.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Rails:
  Enabled: true
Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "lib/docomo-nlu.rb"
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/FilePath:
  CustomTransform:
    DocomoNlu: docomo_nlu
