---
http_interactions:
- request:
    method: put
    uri: http://nlu-external-dev-977165653.ap-northeast-1.elb.amazonaws.com/management/v2.2/projects/212/bots/test_bot/configs
    body:
      encoding: UTF-8
      string: '{"sraix":false,"testUrl":"https://example.com/api/"}'
    headers:
      Content-Type:
      - application/json
      Authorization:
      - NLP f68518ed5a40907ec6b754caeaadc32b0af4920f69955c22749e38e17946ea57
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Thu, 23 Aug 2018 13:53:03 GMT
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Server:
      - Apache
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 23 Aug 2018 13:53:03 GMT
recorded_with: VCR 4.0.0
