---
http_interactions:
- request:
    method: put
    uri: "<Host>/management/v2.6/projects/1/bots/test_bot/configs/"
    body:
      encoding: UTF-8
      string: '{"test_Url":"https://example.com/api/"}'
    headers:
      Content-Type:
      - application/json
      Authorization:
      - "<AdminAccessToken>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: '201'
    headers:
      Date:
      - Wed, 14 Nov 2018 04:56:35 GMT
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Server:
      - Apache
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 14 Nov 2018 04:56:36 GMT
recorded_with: VCR 4.0.0
